In [1]:
import pandas as pd
import os

In [2]:
os.chdir("/ufrc/soltis/shan158538/TragFL_NewAnalysis/OutPut/DE_analysis/Additive_expression_Tms/")

In [3]:
## Input files
nonAdditive = pd.read_table("DESeq2_Tms_nonAdditive_loci.txt", sep = "\t")
Additive = pd.read_table("DESeq2_Tms_Additive_loci.txt", sep = "\t")
nonDE = pd.read_table("DESeq2_noneDE_loci.txt", sep = "\t")
DE = pd.read_table("DESeq2_DE_loci.txt", sep = "\t")

In [23]:
nonAdditive.head()

                                                      baseMean    ...         padj
Tpr_TRINITY_DN1451_c0_g1|Tdu_TRINITY_DN16990_c3_g1  100.236819    ...     0.001337
Tpr_TRINITY_DN10853_c1_g4|Tdu_TRINITY_DN21860_c...  750.334395    ...     0.006242
Tpr_TRINITY_DN12798_c2_g2|Tdu_TRINITY_DN24179_c...   58.686028    ...     0.001516
Tpr_TRINITY_DN8521_c0_g1|Tdu_TRINITY_DN16367_c0_g1    4.080691    ...     0.048222
Tpr_TRINITY_DN11678_c3_g2|Tdu_TRINITY_DN24143_c...   57.367802    ...     0.000751

[5 rows x 6 columns]

In [11]:
## Intersections
nonAdditive_nonDE = pd.merge(nonAdditive, nonDE, how='inner', left_index=True, right_index=True)
nonAdditive_DE = pd.merge(nonAdditive, DE, how='inner', left_index=True, right_index=True)
Additive_nonDE = pd.merge(Additive, nonDE, how='inner', left_index=True, right_index=True)
Additive_DE = pd.merge(Additive, DE, how='inner', left_index=True, right_index=True)

In [24]:
nonAdditive_nonDE.head()

                                                    baseMean_x    ...       padj_y
Tpr_TRINITY_DN10853_c1_g4|Tdu_TRINITY_DN21860_c...  750.334395    ...     0.651873
Tpr_TRINITY_DN12798_c2_g2|Tdu_TRINITY_DN24179_c...   58.686028    ...     0.059050
Tpr_TRINITY_DN8521_c0_g1|Tdu_TRINITY_DN16367_c0_g1    4.080691    ...     0.952824
Tpr_TRINITY_DN13683_c4_g1|Tdu_TRINITY_DN22426_c...   20.461439    ...     0.940505
Tpr_TRINITY_DN15171_c0_g7|Tdu_TRINITY_DN23860_c...    9.738479    ...     0.583258

[5 rows x 12 columns]

In [25]:
## Write out
## columns = [] means do not save any columns, but only save index
nonAdditive_nonDE.to_csv("Tms_nonAdditive_nonDE.txt", columns=[], header=False)
nonAdditive_DE.to_csv("Tms_nonAdditive_DE.txt", columns=[], header=False)
Additive_nonDE.to_csv("Tms_Additive_nonDE.txt", columns=[], header=False)
Additive_DE.to_csv("Tms_Additive_DE.txt", columns=[], header=False)