In [1]:
import pandas as pd
import os

In [2]:
os.chdir("/ufrc/soltis/shan158538/TragFL_NewAnalysis/OutPut/DE_analysis/Additive_expression_Tml/")

In [3]:
## Input files
nonAdditive = pd.read_table("DESeq2_Tml_nonAdditive_loci.txt", sep = "\t")
Additive = pd.read_table("DESeq2_Tml_Additive_loci.txt", sep = "\t")
nonDE = pd.read_table("DESeq2_noneDE_loci.txt", sep = "\t")
DE = pd.read_table("DESeq2_DE_loci.txt", sep = "\t")

In [4]:
nonAdditive.head()

                                                      baseMean    ...         padj
Tpr_TRINITY_DN1451_c0_g1|Tdu_TRINITY_DN16990_c3_g1  103.883699    ...     0.028670
Tpr_TRINITY_DN12798_c2_g2|Tdu_TRINITY_DN24179_c...   53.687590    ...     0.029052
Tpr_TRINITY_DN11712_c1_g8|Tdu_TRINITY_DN19492_c...  439.879994    ...     0.000084
Tpr_TRINITY_DN14614_c1_g6|Tdu_TRINITY_DN1401_c0_g1   71.441805    ...     0.012264
Tpr_TRINITY_DN13868_c2_g1|Tdu_TRINITY_DN24297_c...   16.868174    ...     0.035224

[5 rows x 6 columns]

In [5]:
## Intersections
nonAdditive_nonDE = pd.merge(nonAdditive, nonDE, how='inner', left_index=True, right_index=True)
nonAdditive_DE = pd.merge(nonAdditive, DE, how='inner', left_index=True, right_index=True)
Additive_nonDE = pd.merge(Additive, nonDE, how='inner', left_index=True, right_index=True)
Additive_DE = pd.merge(Additive, DE, how='inner', left_index=True, right_index=True)

In [6]:
nonAdditive_nonDE.head()

                                                    baseMean_x    ...       padj_y
Tpr_TRINITY_DN11712_c1_g8|Tdu_TRINITY_DN19492_c...  439.879994    ...     0.723749
Tpr_TRINITY_DN14614_c1_g6|Tdu_TRINITY_DN1401_c0_g1   71.441805    ...     0.102402
Tpr_TRINITY_DN13868_c2_g1|Tdu_TRINITY_DN24297_c...   16.868174    ...     0.659185
Tpr_TRINITY_DN15138_c2_g2|Tdu_TRINITY_DN19397_c...   73.186485    ...     0.628634
Tpr_TRINITY_DN11436_c1_g7|Tdu_TRINITY_DN21318_c...   40.612571    ...     0.503852

[5 rows x 12 columns]

In [7]:
## Write out
## columns = [] means do not save any columns, but only save index
nonAdditive_nonDE.to_csv("Tml_nonAdditive_nonDE.txt", columns=[], header=False)
nonAdditive_DE.to_csv("Tml_nonAdditive_DE.txt", columns=[], header=False)
Additive_nonDE.to_csv("Tml_Additive_nonDE.txt", columns=[], header=False)
Additive_DE.to_csv("Tml_Additive_DE.txt", columns=[], header=False)